defaultEntryPoints = ["http", "https"]
InsecureSkipVerify = true

[web]
address = ":8080"

[entryPoints]

[entryPoints.http]
address = ":80"

[entryPoints.https]
address = ":443"

[entryPoints.https.tls]

[[entryPoints.https.tls.certificates]]
CertFile = "local.crt"
KeyFile = "local.key"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = true
